// Generated by tools/publish_showcase.py from runs/ — do not edit.
// Scores, spread, action health and the paired comparison behind the
// picker. The numbers are tools/compare_runs.py's, not the page's.
window.PLAGUE_RUNS = {
 "schema_version": "1",
 "featured_seed": "India",
 "baseline": {
  "run_id": "2026-08-26-policy-random",
  "label": "policy/random"
 },
 "primary_metric": "victory_progress",
 "metrics": [
  "victory_progress",
  "extinction_progress",
  "dead_pct",
  "days_to_infect_50pct"
 ],
 "bootstrap": {
  "resamples": 20000,
  "seed": 0
 },
 "superseded": [
  {
   "run_id": "2026-09-01-openai-gemma-4-31b-it",
   "label": "gemma-4-31b-it @ generativelanguage.googleapis.com",
   "superseded_by": "2026-09-02-openai-gemma-4-31b-it",
   "note": "Kept as the evidence for the reply-parser defect, not as a score: 42% of attempted actions were unreadable because an inline reasoning block was parsed as the answer, and --max-tokens 1024 truncated the reply before it reached ACTION:. Re-run clean under 4096 tokens with strip_thoughts in place."
  }
 ],
 "runs": [
  {
   "run_id": "2026-08-26-policy-pass",
   "label": "policy/pass",
   "model": "policy/pass",
   "backend": "policy",
   "endpoint": null,
   "recorded_at": "2026-08-26T04:20:45Z",
   "episodes": 10,
   "metrics": {
    "victory_progress": {
     "field": "victory_progress",
     "mean": 0.7686,
     "sd": 0.108057,
     "sem": 0.034171,
     "ci95": [
      0.691306,
      0.845894
     ],
     "n": 10,
     "episodes": 10
    },
    "extinction_progress": {
     "field": "extinction_progress",
     "mean": 0.0,
     "sd": 0.0,
     "sem": 0.0,
     "ci95": [
      0.0,
      0.0
     ],
     "n": 10,
     "episodes": 10
    },
    "dead_pct": {
     "field": "dead_pct",
     "mean": 0.0,
     "sd": 0.0,
     "sem": 0.0,
     "ci95": [
      0.0,
      0.0
     ],
     "n": 10,
     "episodes": 10
    },
    "days_to_infect_50pct": {
     "field": "days_to_infect_50pct",
     "mean": 447.44444444444446,
     "sd": 52.735451,
     "sem": 17.578484,
     "ci95": [
      406.908461,
      487.980428
     ],
     "n": 9,
     "episodes": 10
    }
   },
   "outcomes": {
    "timeout": 10
   },
   "action_health": {
    "accepted": 0,
    "rejected_unknown": 0,
    "rejected_illegal": 0,
    "passed": 6000,
    "auto_passed": 0,
    "unparsed": 0,
    "rates": {
     "attempted": 0,
     "rejected": 0,
     "rejected_rate": null,
     "illegal_rate": null,
     "unreadable_rate": null
    }
   },
   "wall_time_seconds": 68.3,
   "is_baseline": false,
   "paired": {
    "victory_progress": {
     "diff": -0.09324,
     "bootstrap_ci95": [
      -0.15503,
      -0.04909
     ],
     "t_ci95": [
      -0.16056,
      -0.02592
     ],
     "seeds_won": {
      "wins": 0,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0,
       0.2775
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": false
     },
     "verdict": "separated on the paired test; independent intervals overlap. The runs share their seeds, so the paired test is the one that applies \u2014 but the weaker reading belongs in the record"
    },
    "extinction_progress": {
     "diff": -0.29102,
     "bootstrap_ci95": [
      -0.33553,
      -0.24107
     ],
     "t_ci95": [
      -0.349391,
      -0.232649
     ],
     "seeds_won": {
      "wins": 0,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0,
       0.2775
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "dead_pct": {
     "diff": -27.647,
     "bootstrap_ci95": [
      -31.876,
      -22.903
     ],
     "t_ci95": [
      -33.191768,
      -22.102232
     ],
     "seeds_won": {
      "wins": 0,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0,
       0.2775
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "days_to_infect_50pct": {
     "diff": 198.888889,
     "bootstrap_ci95": [
      182.444444,
      213.888889
     ],
     "t_ci95": [
      179.001934,
      218.775844
     ],
     "seeds_won": {
      "wins": 0,
      "decided": 9,
      "n": 9,
      "wilson95": [
       0.0,
       0.2992
      ]
     },
     "n": 9,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    }
   },
   "replay": "2026-08-26-policy-pass",
   "replay_file": "policy-pass.js"
  },
  {
   "run_id": "2026-08-26-policy-random",
   "label": "policy/random",
   "model": "policy/random",
   "backend": "policy",
   "endpoint": null,
   "recorded_at": "2026-08-26T04:21:22Z",
   "episodes": 10,
   "metrics": {
    "victory_progress": {
     "field": "victory_progress",
     "mean": 0.8618399999999999,
     "sd": 0.055558,
     "sem": 0.017569,
     "ci95": [
      0.822099,
      0.901581
     ],
     "n": 10,
     "episodes": 10
    },
    "extinction_progress": {
     "field": "extinction_progress",
     "mean": 0.29102,
     "sd": 0.081602,
     "sem": 0.025805,
     "ci95": [
      0.232649,
      0.349391
     ],
     "n": 10,
     "episodes": 10
    },
    "dead_pct": {
     "field": "dead_pct",
     "mean": 27.647000000000002,
     "sd": 7.751589,
     "sem": 2.451268,
     "ci95": [
      22.102232,
      33.191768
     ],
     "n": 10,
     "episodes": 10
    },
    "days_to_infect_50pct": {
     "field": "days_to_infect_50pct",
     "mean": 251.1,
     "sd": 30.827297,
     "sem": 9.748447,
     "ci95": [
      229.049013,
      273.150987
     ],
     "n": 10,
     "episodes": 10
    }
   },
   "outcomes": {
    "cured": 10
   },
   "action_health": {
    "accepted": 394,
    "rejected_unknown": 0,
    "rejected_illegal": 0,
    "passed": 2891,
    "auto_passed": 0,
    "unparsed": 0,
    "rates": {
     "attempted": 394,
     "rejected": 0,
     "rejected_rate": 0.0,
     "illegal_rate": 0.0,
     "unreadable_rate": 0.0
    }
   },
   "wall_time_seconds": 35.7,
   "is_baseline": true,
   "paired": {},
   "replay": "2026-08-26-policy-random",
   "replay_file": "policy-random.js"
  },
  {
   "run_id": "2026-08-26-policy-greedy",
   "label": "policy/greedy",
   "model": "policy/greedy",
   "backend": "policy",
   "endpoint": null,
   "recorded_at": "2026-08-26T04:21:54Z",
   "episodes": 10,
   "metrics": {
    "victory_progress": {
     "field": "victory_progress",
     "mean": 0.75719,
     "sd": 0.085022,
     "sem": 0.026886,
     "ci95": [
      0.696373,
      0.818007
     ],
     "n": 10,
     "episodes": 10
    },
    "extinction_progress": {
     "field": "extinction_progress",
     "mean": 0.26103,
     "sd": 0.063721,
     "sem": 0.02015,
     "ci95": [
      0.21545,
      0.30661
     ],
     "n": 10,
     "episodes": 10
    },
    "dead_pct": {
     "field": "dead_pct",
     "mean": 24.8,
     "sd": 6.054354,
     "sem": 1.914555,
     "ci95": [
      20.469277,
      29.130723
     ],
     "n": 10,
     "episodes": 10
    },
    "days_to_infect_50pct": {
     "field": "days_to_infect_50pct",
     "mean": 236.8,
     "sd": 30.745551,
     "sem": 9.722597,
     "ci95": [
      214.807486,
      258.792514
     ],
     "n": 10,
     "episodes": 10
    }
   },
   "outcomes": {
    "cured": 10
   },
   "action_health": {
    "accepted": 388,
    "rejected_unknown": 0,
    "rejected_illegal": 0,
    "passed": 2520,
    "auto_passed": 0,
    "unparsed": 0,
    "rates": {
     "attempted": 388,
     "rejected": 0,
     "rejected_rate": 0.0,
     "illegal_rate": 0.0,
     "unreadable_rate": 0.0
    }
   },
   "wall_time_seconds": 30.9,
   "is_baseline": false,
   "paired": {
    "victory_progress": {
     "diff": -0.10465,
     "bootstrap_ci95": [
      -0.14876,
      -0.06395
     ],
     "t_ci95": [
      -0.157187,
      -0.052113
     ],
     "seeds_won": {
      "wins": 1,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0179,
       0.4042
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "extinction_progress": {
     "diff": -0.02999,
     "bootstrap_ci95": [
      -0.0646,
      0.0129
     ],
     "t_ci95": [
      -0.078088,
      0.018108
     ],
     "seeds_won": {
      "wins": 2,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0567,
       0.5098
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    },
    "dead_pct": {
     "diff": -2.847,
     "bootstrap_ci95": [
      -6.134,
      1.227
     ],
     "t_ci95": [
      -7.415274,
      1.721274
     ],
     "seeds_won": {
      "wins": 2,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0567,
       0.5098
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    },
    "days_to_infect_50pct": {
     "diff": -14.3,
     "bootstrap_ci95": [
      -25.2,
      -2.7
     ],
     "t_ci95": [
      -28.133588,
      -0.466412
     ],
     "seeds_won": {
      "wins": 7,
      "decided": 9,
      "n": 10,
      "wilson95": [
       0.4526,
       0.9368
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": false
     },
     "verdict": "separated on the paired test; independent intervals overlap. The runs share their seeds, so the paired test is the one that applies \u2014 but the weaker reading belongs in the record"
    }
   },
   "replay": "2026-08-26-policy-greedy",
   "replay_file": "policy-greedy.js"
  },
  {
   "run_id": "2026-08-26-policy-expert",
   "label": "policy/expert",
   "model": "policy/expert",
   "backend": "policy",
   "endpoint": null,
   "recorded_at": "2026-08-26T04:22:47Z",
   "episodes": 10,
   "metrics": {
    "victory_progress": {
     "field": "victory_progress",
     "mean": 0.9987,
     "sd": 0.000573,
     "sem": 0.000181,
     "ci95": [
      0.99829,
      0.99911
     ],
     "n": 10,
     "episodes": 10
    },
    "extinction_progress": {
     "field": "extinction_progress",
     "mean": 0.53115,
     "sd": 0.028454,
     "sem": 0.008998,
     "ci95": [
      0.510797,
      0.551503
     ],
     "n": 10,
     "episodes": 10
    },
    "dead_pct": {
     "field": "dead_pct",
     "mean": 50.458,
     "sd": 2.703548,
     "sem": 0.854937,
     "ci95": [
      48.524132,
      52.391868
     ],
     "n": 10,
     "episodes": 10
    },
    "days_to_infect_50pct": {
     "field": "days_to_infect_50pct",
     "mean": 243.0,
     "sd": 30.254476,
     "sem": 9.567305,
     "ci95": [
      221.358755,
      264.641245
     ],
     "n": 10,
     "episodes": 10
    }
   },
   "outcomes": {
    "cured": 6,
    "infected_all": 4
   },
   "action_health": {
    "accepted": 413,
    "rejected_unknown": 0,
    "rejected_illegal": 0,
    "passed": 3678,
    "auto_passed": 0,
    "unparsed": 0,
    "rates": {
     "attempted": 413,
     "rejected": 0,
     "rejected_rate": 0.0,
     "illegal_rate": 0.0,
     "unreadable_rate": 0.0
    }
   },
   "wall_time_seconds": 52.1,
   "is_baseline": false,
   "paired": {
    "victory_progress": {
     "diff": 0.13686,
     "bootstrap_ci95": [
      0.10428,
      0.1693
     ],
     "t_ci95": [
      0.097304,
      0.176416
     ],
     "seeds_won": {
      "wins": 10,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.7225,
       1.0
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "extinction_progress": {
     "diff": 0.24013,
     "bootstrap_ci95": [
      0.19446,
      0.29061
     ],
     "t_ci95": [
      0.180964,
      0.299296
     ],
     "seeds_won": {
      "wins": 10,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.7225,
       1.0
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "dead_pct": {
     "diff": 22.811,
     "bootstrap_ci95": [
      18.472,
      27.606
     ],
     "t_ci95": [
      17.190093,
      28.431907
     ],
     "seeds_won": {
      "wins": 10,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.7225,
       1.0
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "days_to_infect_50pct": {
     "diff": -8.1,
     "bootstrap_ci95": [
      -18.6,
      3.4
     ],
     "t_ci95": [
      -21.560326,
      5.360326
     ],
     "seeds_won": {
      "wins": 7,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.3968,
       0.8922
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    }
   },
   "replay": "2026-08-26-policy-expert",
   "replay_file": "policy-expert.js"
  },
  {
   "run_id": "2026-08-26-ollama-llama3-2",
   "label": "llama3.2 (ollama)",
   "model": "ollama/llama3.2",
   "backend": "ollama",
   "endpoint": "http://localhost:11434",
   "recorded_at": "2026-08-26T04:59:17Z",
   "episodes": 10,
   "metrics": {
    "victory_progress": {
     "field": "victory_progress",
     "mean": 0.83972,
     "sd": 0.050662,
     "sem": 0.016021,
     "ci95": [
      0.803481,
      0.875959
     ],
     "n": 10,
     "episodes": 10
    },
    "extinction_progress": {
     "field": "extinction_progress",
     "mean": 0.24096,
     "sd": 0.075384,
     "sem": 0.023838,
     "ci95": [
      0.187037,
      0.294883
     ],
     "n": 10,
     "episodes": 10
    },
    "dead_pct": {
     "field": "dead_pct",
     "mean": 22.892,
     "sd": 7.162474,
     "sem": 2.264973,
     "ci95": [
      17.76863,
      28.01537
     ],
     "n": 10,
     "episodes": 10
    },
    "days_to_infect_50pct": {
     "field": "days_to_infect_50pct",
     "mean": 235.8,
     "sd": 23.817827,
     "sem": 7.531858,
     "ci95": [
      218.762937,
      252.837063
     ],
     "n": 10,
     "episodes": 10
    }
   },
   "outcomes": {
    "cured": 10
   },
   "action_health": {
    "accepted": 386,
    "rejected_unknown": 0,
    "rejected_illegal": 5,
    "passed": 0,
    "auto_passed": 2695,
    "unparsed": 0,
    "rates": {
     "attempted": 391,
     "rejected": 5,
     "rejected_rate": 0.0128,
     "illegal_rate": 0.0128,
     "unreadable_rate": 0.0
    }
   },
   "wall_time_seconds": 1822.8,
   "is_baseline": false,
   "paired": {
    "victory_progress": {
     "diff": -0.02212,
     "bootstrap_ci95": [
      -0.06583,
      0.02158
     ],
     "t_ci95": [
      -0.074987,
      0.030747
     ],
     "seeds_won": {
      "wins": 3,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.1078,
       0.6032
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    },
    "extinction_progress": {
     "diff": -0.05006,
     "bootstrap_ci95": [
      -0.10544,
      0.00516
     ],
     "t_ci95": [
      -0.117631,
      0.017511
     ],
     "seeds_won": {
      "wins": 3,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.1078,
       0.6032
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    },
    "dead_pct": {
     "diff": -4.755,
     "bootstrap_ci95": [
      -10.016,
      0.49
     ],
     "t_ci95": [
      -11.173804,
      1.663804
     ],
     "seeds_won": {
      "wins": 3,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.1078,
       0.6032
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    },
    "days_to_infect_50pct": {
     "diff": -15.3,
     "bootstrap_ci95": [
      -24.5,
      -8.0
     ],
     "t_ci95": [
      -25.500202,
      -5.099798
     ],
     "seeds_won": {
      "wins": 10,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.7225,
       1.0
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": false
     },
     "verdict": "separated on the paired test; independent intervals overlap. The runs share their seeds, so the paired test is the one that applies \u2014 but the weaker reading belongs in the record"
    }
   },
   "replay": null,
   "replay_file": null
  },
  {
   "run_id": "2026-08-26-ollama-mistral-7b",
   "label": "mistral:7b (ollama)",
   "model": "ollama/mistral:7b",
   "backend": "ollama",
   "endpoint": "http://localhost:11434",
   "recorded_at": "2026-08-26T05:53:32Z",
   "episodes": 10,
   "metrics": {
    "victory_progress": {
     "field": "victory_progress",
     "mean": 0.73651,
     "sd": 0.077587,
     "sem": 0.024535,
     "ci95": [
      0.681011,
      0.792009
     ],
     "n": 10,
     "episodes": 10
    },
    "extinction_progress": {
     "field": "extinction_progress",
     "mean": 0.21278000000000002,
     "sd": 0.059497,
     "sem": 0.018814,
     "ci95": [
      0.170222,
      0.255338
     ],
     "n": 10,
     "episodes": 10
    },
    "dead_pct": {
     "field": "dead_pct",
     "mean": 20.214,
     "sd": 5.652546,
     "sem": 1.787492,
     "ci95": [
      16.170693,
      24.257307
     ],
     "n": 10,
     "episodes": 10
    },
    "days_to_infect_50pct": {
     "field": "days_to_infect_50pct",
     "mean": 243.1,
     "sd": 21.768734,
     "sem": 6.883878,
     "ci95": [
      227.528668,
      258.671332
     ],
     "n": 10,
     "episodes": 10
    }
   },
   "outcomes": {
    "cured": 10
   },
   "action_health": {
    "accepted": 375,
    "rejected_unknown": 0,
    "rejected_illegal": 0,
    "passed": 0,
    "auto_passed": 2493,
    "unparsed": 0,
    "rates": {
     "attempted": 375,
     "rejected": 0,
     "rejected_rate": 0.0,
     "illegal_rate": 0.0,
     "unreadable_rate": 0.0
    }
   },
   "wall_time_seconds": 3249.4,
   "is_baseline": false,
   "paired": {
    "victory_progress": {
     "diff": -0.12533,
     "bootstrap_ci95": [
      -0.18917,
      -0.05899
     ],
     "t_ci95": [
      -0.205559,
      -0.045101
     ],
     "seeds_won": {
      "wins": 2,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0567,
       0.5098
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "extinction_progress": {
     "diff": -0.07824,
     "bootstrap_ci95": [
      -0.13346,
      -0.01794
     ],
     "t_ci95": [
      -0.149607,
      -0.006873
     ],
     "seeds_won": {
      "wins": 2,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0567,
       0.5098
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": false
     },
     "verdict": "separated on the paired test; independent intervals overlap. The runs share their seeds, so the paired test is the one that applies \u2014 but the weaker reading belongs in the record"
    },
    "dead_pct": {
     "diff": -7.433,
     "bootstrap_ci95": [
      -12.679,
      -1.704
     ],
     "t_ci95": [
      -14.212632,
      -0.653368
     ],
     "seeds_won": {
      "wins": 2,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.0567,
       0.5098
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": false
     },
     "verdict": "separated on the paired test; independent intervals overlap. The runs share their seeds, so the paired test is the one that applies \u2014 but the weaker reading belongs in the record"
    },
    "days_to_infect_50pct": {
     "diff": -8.0,
     "bootstrap_ci95": [
      -19.1,
      3.5
     ],
     "t_ci95": [
      -21.886707,
      5.886707
     ],
     "seeds_won": {
      "wins": 6,
      "decided": 9,
      "n": 10,
      "wilson95": [
       0.3542,
       0.8794
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    }
   },
   "replay": null,
   "replay_file": null
  },
  {
   "run_id": "2026-08-26-ollama-gemma3-4b",
   "label": "gemma3:4b (ollama)",
   "model": "ollama/gemma3:4b",
   "backend": "ollama",
   "endpoint": "http://localhost:11434",
   "recorded_at": "2026-08-26T06:50:29Z",
   "episodes": 10,
   "metrics": {
    "victory_progress": {
     "field": "victory_progress",
     "mean": 0.86463,
     "sd": 0.044117,
     "sem": 0.013951,
     "ci95": [
      0.833073,
      0.896187
     ],
     "n": 10,
     "episodes": 10
    },
    "extinction_progress": {
     "field": "extinction_progress",
     "mean": 0.30124,
     "sd": 0.066559,
     "sem": 0.021048,
     "ci95": [
      0.25363,
      0.34885
     ],
     "n": 10,
     "episodes": 10
    },
    "dead_pct": {
     "field": "dead_pct",
     "mean": 28.617,
     "sd": 6.323329,
     "sem": 1.999612,
     "ci95": [
      24.093877,
      33.140123
     ],
     "n": 10,
     "episodes": 10
    },
    "days_to_infect_50pct": {
     "field": "days_to_infect_50pct",
     "mean": 222.3,
     "sd": 29.612497,
     "sem": 9.364294,
     "ci95": [
      201.117967,
      243.482033
     ],
     "n": 10,
     "episodes": 10
    }
   },
   "outcomes": {
    "cured": 10
   },
   "action_health": {
    "accepted": 393,
    "rejected_unknown": 2,
    "rejected_illegal": 103,
    "passed": 0,
    "auto_passed": 2634,
    "unparsed": 0,
    "rates": {
     "attempted": 498,
     "rejected": 105,
     "rejected_rate": 0.2108,
     "illegal_rate": 0.2068,
     "unreadable_rate": 0.004
    }
   },
   "wall_time_seconds": 3411.5,
   "is_baseline": false,
   "paired": {
    "victory_progress": {
     "diff": 0.00279,
     "bootstrap_ci95": [
      -0.02816,
      0.03522
     ],
     "t_ci95": [
      -0.03556,
      0.04114
     ],
     "seeds_won": {
      "wins": 7,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.3968,
       0.8922
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    },
    "extinction_progress": {
     "diff": 0.01022,
     "bootstrap_ci95": [
      -0.03363,
      0.05291
     ],
     "t_ci95": [
      -0.042485,
      0.062925
     ],
     "seeds_won": {
      "wins": 5,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.2366,
       0.7634
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    },
    "dead_pct": {
     "diff": 0.97,
     "bootstrap_ci95": [
      -3.195,
      5.025
     ],
     "t_ci95": [
      -4.036038,
      5.976038
     ],
     "seeds_won": {
      "wins": 5,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.2366,
       0.7634
      ]
     },
     "n": 10,
     "separated": {
      "paired": false,
      "independent": false
     },
     "verdict": "not separated \u2014 the paired differences are consistent with zero"
    },
    "days_to_infect_50pct": {
     "diff": -28.8,
     "bootstrap_ci95": [
      -36.3,
      -21.2
     ],
     "t_ci95": [
      -38.100828,
      -19.499172
     ],
     "seeds_won": {
      "wins": 10,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.7225,
       1.0
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": false
     },
     "verdict": "separated on the paired test; independent intervals overlap. The runs share their seeds, so the paired test is the one that applies \u2014 but the weaker reading belongs in the record"
    }
   },
   "replay": null,
   "replay_file": null
  },
  {
   "run_id": "2026-09-02-openai-gemma-4-31b-it",
   "label": "gemma-4-31b-it @ generativelanguage.googleapis.com",
   "model": "openai/gemma-4-31b-it",
   "backend": "openai",
   "endpoint": "https://generativelanguage.googleapis.com/v1beta/openai",
   "recorded_at": "2026-09-02T16:08:42Z",
   "episodes": 10,
   "metrics": {
    "victory_progress": {
     "field": "victory_progress",
     "mean": 0.9269399999999999,
     "sd": 0.055393,
     "sem": 0.017517,
     "ci95": [
      0.887317,
      0.966563
     ],
     "n": 10,
     "episodes": 10
    },
    "extinction_progress": {
     "field": "extinction_progress",
     "mean": 0.48630000000000007,
     "sd": 0.07822,
     "sem": 0.024735,
     "ci95": [
      0.430349,
      0.542251
     ],
     "n": 10,
     "episodes": 10
    },
    "dead_pct": {
     "field": "dead_pct",
     "mean": 46.199,
     "sd": 7.432884,
     "sem": 2.350484,
     "ci95": [
      40.882204,
      51.515796
     ],
     "n": 10,
     "episodes": 10
    },
    "days_to_infect_50pct": {
     "field": "days_to_infect_50pct",
     "mean": 226.1,
     "sd": 23.941828,
     "sem": 7.571071,
     "ci95": [
      208.974238,
      243.225762
     ],
     "n": 10,
     "episodes": 10
    }
   },
   "outcomes": {
    "cured": 10
   },
   "action_health": {
    "accepted": 423,
    "rejected_unknown": 0,
    "rejected_illegal": 0,
    "passed": 404,
    "auto_passed": 2697,
    "unparsed": 28,
    "rates": {
     "attempted": 423,
     "rejected": 0,
     "rejected_rate": 0.0,
     "illegal_rate": 0.0,
     "unreadable_rate": 0.0
    }
   },
   "wall_time_seconds": 33786.4,
   "is_baseline": false,
   "paired": {
    "victory_progress": {
     "diff": 0.0651,
     "bootstrap_ci95": [
      0.02838,
      0.10335
     ],
     "t_ci95": [
      0.020198,
      0.110002
     ],
     "seeds_won": {
      "wins": 8,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.4902,
       0.9433
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": false
     },
     "verdict": "separated on the paired test; independent intervals overlap. The runs share their seeds, so the paired test is the one that applies \u2014 but the weaker reading belongs in the record"
    },
    "extinction_progress": {
     "diff": 0.19528,
     "bootstrap_ci95": [
      0.14456,
      0.24592
     ],
     "t_ci95": [
      0.133424,
      0.257136
     ],
     "seeds_won": {
      "wins": 10,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.7225,
       1.0
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "dead_pct": {
     "diff": 18.552,
     "bootstrap_ci95": [
      13.732,
      23.363
     ],
     "t_ci95": [
      12.673864,
      24.430136
     ],
     "seeds_won": {
      "wins": 10,
      "decided": 10,
      "n": 10,
      "wilson95": [
       0.7225,
       1.0
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": true
     },
     "verdict": "separated \u2014 paired test and independent intervals agree"
    },
    "days_to_infect_50pct": {
     "diff": -25.0,
     "bootstrap_ci95": [
      -36.8,
      -14.1
     ],
     "t_ci95": [
      -39.004928,
      -10.995072
     ],
     "seeds_won": {
      "wins": 9,
      "decided": 9,
      "n": 10,
      "wilson95": [
       0.7008,
       1.0
      ]
     },
     "n": 10,
     "separated": {
      "paired": true,
      "independent": false
     },
     "verdict": "separated on the paired test; independent intervals overlap. The runs share their seeds, so the paired test is the one that applies \u2014 but the weaker reading belongs in the record"
    }
   },
   "replay": null,
   "replay_file": null
  }
 ]
};
